package: hijing
description: HIJING heavy-ion jet interaction generator
version: "1.383bs.2"
tag: "1.383bs.2"
sources:
  - https://lcgpackages.web.cern.ch/tarFiles/sources/MCGeneratorsTarFiles/hijing-1.383bs.2-src.tgz
build_requires:
  - bits-recipe-tools
  - "GCC-Toolchain:(?!osx)"
license: LicenseRef-HIJING
patches:
  - hijing-1.383bs.2.patch
---
#!/bin/bash -e
##############################
. $(bits-include AutoToolsRecipe)
##############################
MODULE_OPTIONS="--lib"
##############################
function Configure() {
  # HIJING configure does not understand --prefix (prints "wrong option.
  # Ignored." and continues), so we install manually in Make().
  export F77=${FC:-gfortran}
  # The configure script hardcodes 'g77' into the generated Makeshared.subdir.
  # Replace it before running configure so the generated output uses gfortran.
  perl -i -pe "s/\bg77\b/${F77}/g" configure
  ./configure
}

function Make() {
  # Replace the hardcoded 'g77' compiler name in all build-system files
  # (Makefiles, config files, templates) immediately before invoking make,
  # so that any files regenerated by configure are also caught.
  # Fortran source files (.f/.F) are excluded.
  grep -rl "g77" . | grep -Ev '\.(f|F|f90|F90|for|FOR)$' | \
    xargs perl -i -pe "s/g77/${F77}/g"
  # macOS: the vendored Makeshared.subdir links the shared lib with ELF flags
  # ($(CXX) ... -shared -Wl,-soname,...), which macOS ld rejects ("unknown
  # options: -soname"). Rewrite that link to macOS conventions: -dynamiclib,
  # allow undefined symbols (two-level namespace), and reserve Mach-O header pad
  # so bits' relocate-me.sh can rewrite the install name. Linux keeps the ELF
  # flags. Idempotent via the grep guard.
  if [ "$(uname)" = Darwin ] && ! grep -q 'dynamiclib' Makeshared.subdir; then
    perl -i -pe 's/-shared -Wl,-soname,.*$/-dynamiclib -Wl,-undefined,dynamic_lookup -Wl,-headerpad_max_install_names/' Makeshared.subdir
  fi
  make ${JOBS:+-j $JOBS}
}

function MakeInstall() {
  # HIJING's Makefile has no 'install' target and configure ignored --prefix,
  # so the default `make install` fails ("No rule to make target 'install'").
  # Install the built library (and optional COMMON-block headers) manually.
  mkdir -p "${INSTALLROOT}/lib"
  cp -p lib/libhijing.* "${INSTALLROOT}/lib/"
  # Fortran COMMON-block include files, if the tarball ships them.  Use an
  # if-block (not `[[ ]] && {...}`) so a missing include/ dir does not make
  # MakeInstall() return non-zero and abort the build under `set -e`.
  if [[ -d include ]]; then
    mkdir -p "${INSTALLROOT}/include"
    cp -rp include/. "${INSTALLROOT}/include/"
  fi
}
