package: hijing
description: HIJING heavy-ion jet interaction generator
version: "1.383bs.2"
tag: "1.383bs.2"
sources:
  - https://lcgpackages.web.cern.ch/tarFiles/sources/MCGeneratorsTarFiles/hijing-1.383bs.2-src.tgz
build_requires:
  - bits-recipe-tools
  - "GCC-Toolchain:(?!osx)"
license: LicenseRef-HIJING
patches:
  - hijing-1.383bs.2.patch
---
#!/bin/bash -e
##############################
. $(bits-include AutoToolsRecipe)
##############################
MODULE_OPTIONS="--lib"
##############################
function Configure() {
  # HIJING configure does not understand --prefix (prints "wrong option.
  # Ignored." and continues), so we install manually in Make().
  export F77=${FC:-gfortran}
  # The configure script hardcodes 'g77' into the generated Makeshared.subdir.
  # Replace it before running configure so the generated output uses gfortran.
  sed -i "s/\bg77\b/${F77}/g" configure
  ./configure
}

function Make() {
  # Replace the hardcoded 'g77' compiler name in all build-system files
  # (Makefiles, config files, templates) immediately before invoking make,
  # so that any files regenerated by configure are also caught.
  # Fortran source files (.f/.F) are excluded.
  grep -rl "g77" . | grep -Ev '\.(f|F|f90|F90|for|FOR)$' | \
    xargs --no-run-if-empty sed -i "s/g77/${F77}/g"
  make ${JOBS:+-j $JOBS}
  # configure ignored --prefix so install manually.
  mkdir -p "${INSTALLROOT}/lib"
  cp -p lib/libhijing.* "${INSTALLROOT}/lib/"
  # Fortran COMMON-block include files, if the tarball ships them.  Use an
  # if-block (not `[[ ]] && {...}`) so a missing include/ dir does not make
  # Make() return non-zero and abort the build under `set -e`.
  if [[ -d include ]]; then
    mkdir -p "${INSTALLROOT}/include"
    cp -rp include/. "${INSTALLROOT}/include/"
  fi
}
