package: yoda
description: YODA (Yet more Objects for Data Analysis) histogram library
version: "1.9.0"
tag: "1.9.0"
sources:
  - https://lcgpackages.web.cern.ch/tarFiles/sources/MCGeneratorsTarFiles/YODA-1.9.0.tar.gz
requires:
  - Python
  - ROOT
build_requires:
  - bits-recipe-tools
  - "GCC-Toolchain:(?!osx)"
  # Cython is needed at build time to regenerate the pyext C++ from the .pyx
  # sources: the *.cpp shipped in the tarball target an old CPython C API and do
  # not compile against Python >= 3.12 (3.13 here).
  - cython
license: GPL-3.0-or-later
---
#!/bin/bash -e
##############################
. $(bits-include AutoToolsRecipe)
. $(bits-include BitsPython)
##############################
MODULE_OPTIONS="--bin --lib --pysite"
##############################
function Configure() {
  # Pass PYTHON explicitly so configure doesn't try to find "python$PYTHON_VERSION"
  # (e.g. python3.13.11) when PYTHON_VERSION is set to the full version string.
  # YODA 1.9.0 does not use Boost; drop the unrecognised --with-boost option.
  #
  # The pyext C++ shipped in the tarball (pyext/yoda/{core,util,rootcompat}.cpp)
  # was generated by an old Cython and uses CPython internals removed in 3.12/3.13
  # (PyThreadState.curexc_*, _PyErr_StackItem.exc_*, the old PyCode_New signature,
  # longintrepr.h, _PyGen_Send, ...), so it cannot compile against Python 3.13.
  # The cure is to regenerate it from the .pyx with a modern Cython (bits ships
  # Cython 3.2.4).  YODA's configure rebuilds the C++ only when it detects
  # "Cython >= 0.24" — both importable by $PYTHON and as a `cython` executable —
  # so put the bits-built Cython on PATH and PYTHONPATH first.  YODA's Configure()
  # is not a subshell, so this export reaches the Make step too.
  bits_enable_cython
  # configure's "force rebuild" only touches core.pyx, which would leave
  # util.cpp / rootcompat.cpp stale.  Remove every generated file so make
  # re-runs Cython for all of them (and fails loudly if Cython is somehow
  # missing, rather than compiling the stale C++).
  rm -f pyext/yoda/core.cpp pyext/yoda/core.h pyext/yoda/util.cpp pyext/yoda/rootcompat.cpp
  ./configure --prefix=$INSTALLROOT \
    CXXFLAGS=-Wno-register \
    PYTHON="${PYTHON_ROOT:+${PYTHON_ROOT}/bin/python3}"
}
